server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/db2019
    username: root
    password: 123456

# 如不使用redis，请将以下配置删除
  redis:
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    host: 127.0.0.1 # Redis的地址
    port: 6379 # Redis的端口
    password: 123456 # Redis的密码
    timeout: 60000 # 连接超时时间（毫秒）
# 使用lettuce最为redis客户端
    lettuce:
      shutdown-timeout: 60000ms # 关闭超时时间
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 20000ms # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 1 # 连接池中的最小空闲连接 默认 0
        max-idle: 20 # 连接池中的最大空闲连接 默认 8
  cache:
    type: redis #spring cache类型
# 如不使用redis，请将以上配置删除

eureka:
  client:
    fetch-registry: true
    #表示向注册中心注册自己
    register-with-eureka: true
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示ip地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities # 所有Entity别名类所在包

