server:
  port: 9527
spring:
  application:
    name: cloud-getway
  #配置网关
  cloud:
    gateway:
     discovery:
      locator:
        enabled: false # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
     routes:
        - id: payment_routh  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/serverPort/**  # 断言,路径相匹配的进行路由
            - After=2020-05-17T12:54:12.363+08:00[Asia/Shanghai]  # 在什么时间后生效

        - id: payment_routh2  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  # 断言,路径相匹配的进行路由
            - After=2020-05-17T12:54:12.363+08:00[Asia/Shanghai]  # 在什么时间后生效

eureka:
  instance:
    hostname: cloud-getway-service
  client:
    fetch-registry: true
    #表示向注册中心注册自己
    register-with-eureka: true
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


