server:
  port: 80

spring:
  application:
    name: cloud-cousumer-hystrix-order

eureka:
  client:
    fetch-registry: true
    #表示不会向注册中心注册自己
    register-with-eureka: false
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true  #访问路径可以显示ip地址

# 设置Feign客户端超时时间（openFeign默认支持Ribbon）
ribbon:
#指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
 ConnectTimeout: 8000
# 指的是建立连接后从服务器读取数据所用的时间
 ReadTimeout: 8000

# Feign日志
logging:
  level:
   com.atguigu.springcloud.service.PaymentFeignService: debug

# 开启Hystrix
feign:
  hystrix:
    enabled: true





